######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 13 14:10:25 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += "/ad/eng/users/p/k/pkmurphy/Desktop/EC535 Project/qt/github Regalis/QSSnake-master/." \
               .

# Input
HEADERS += qssnake.hpp
SOURCES += main.cpp qssnake.cpp
