######################################################################
# Automatically generated by qmake (2.01a) Mon Dec 5 16:08:19 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qssnake.hpp
SOURCES += main.cpp qssnake.cpp
